Deltares/Ribasim-NL

.github/workflows/python_tests.yml, .typos.toml, environment.yml, notebooks/nl-kunstwerken.ipynb, notebooks/uitlaten_inlaten.ipynb, src/hydamo/environment.yml, src/hydamo/tests/test_datamodel.py
Contains two notebooks with structures at RWS boundaries:
- `nl-kunstwerken.ipynb` to create a GeoPackage from the data in https://samenwerkenaankunstwerken.nl/#. Writes to: https://deltares.thegood.cloud/f/54241
- `uitlaten_inlaten.ipynb` to create a HyDAMO GeoPackage from our own collection of inlets_outlets. Writes to: https://deltares.thegood.cloud/f/52625
`environment.yml` is moved and considered to be a project-yml. For now we only need openpyxl as extra so we can read Excel-files in Pandas. Notebooks can run with this environment, after including hydamo from the src/hydamo dir added by:
```
pip install -e .
`` 
In the activated enviroment
=> Process inlets outlets

ruff.toml, scripts/ruff_ignore_test.py
allow user to 'dump' un-used script-level files in the scripts-folder
=> Allow scripts

src/ribasim_nl/ribasim_nl/__init__.py, src/ribasim_nl/ribasim_nl/network.py, src/ribasim_nl/tests/test_cloud.py, src/ribasim_nl/tests/test_network.py
Create networks from lines_gdf, including:
- snapping of nodes within tolerance
- filling gaps between lines within tolerance
- dissolving lines shorter than tolerance
- splitting lines where segments intersect nodes
links with issues #11 and #1
=> Network class

docs/CNAME, docs/_quarto.yml
Otherwise the domain setting will reset after a new deployment (sooner rather than later). edit: already happened.
=> Add CNAME file for docs deployment.

.github/workflows/docs.yml, .github/workflows/python_lint.yml, .github/workflows/python_tests.yml
to see whether they solved our lock file being out of date, which was worked around in #144 (this reverts that).
=> Try latest pixi

pixi.lock
To use the latest dependencies
=> Update pixi lock file

notebooks/brabantse_delta/01_fix_model_network.py, notebooks/drents_overijsselse_delta/01_fix_model_network.py, notebooks/hunze_en_aas/01_fix_model_network.py, notebooks/limburg/01_fix_model_network.py, notebooks/noorderzijlvest/01_fix_model_network.py, notebooks/rijn_en_ijssel/01_fix_model_network.py, notebooks/samenvoegen_modellen.py, notebooks/stichtse_rijnlanden/01_fix_model_network.py, notebooks/vallei_en_veluwe/01_fix_model_network.py, notebooks/vechtstromen/01_fix_model_network.py, src/ribasim_nl/ribasim_nl/reset_static_tables.py
reset_static_tables naar plausibele waarden bij  fix en samenvoeg scripts
=> reset_static_tables

src/ribasim_nl/ribasim_nl/model.py
Wat methods in ribasim_nl.Model om het bovenstroomse basin te bepalen v.e. node. Handig voor parameterisatie. Tegelijk ook de upstream en downstream edges van een node opvraagbaar gemaakt.
Zie bijvoorbeeld bovenstrooms basin van Lorentzsluizen
=> us basin/edges ds edges

notebooks/samenvoegen_modellen.py, src/ribasim_nl/ribasim_nl/__init__.py, src/ribasim_nl/ribasim_nl/concat.py, src/ribasim_nl/ribasim_nl/model.py, src/ribasim_nl/ribasim_nl/reset_index.py, src/ribasim_nl/ribasim_nl/run_model.py
Fixes #213
Fixes #222
- handhaven node-ids #213  
- kunnen draaien in dev-mode, zodat modellen kunnen worden gedraaid bij samenvoegen: #222
=> prefix_index

src/ribasim_nl/ribasim_nl/model.py
=> Fix rename edge to link in a backwards compatible way.

.github/workflows/pixi_auto_update.yml
We need both repositories for this to work.
=> Pixi auto update fixes

notebooks/check_manning.py, notebooks/check_manning_results.py, src/ribasim_nl/ribasim_nl/model.py, src/ribasim_nl/ribasim_nl/parametrization/manning_resistance_table.py
fixes #258
Please advise on the use of manning-nodes
=> Manning nodes

notebooks/aa_en_maas/03_parameterize_model.py, src/peilbeheerst_model/peilbeheerst_model/controle_output.py
@rbruijnshkv, controle_output can handle links (and edges) now. Some minimal changes to the parameterize script
=> Links for AAM

pixi.lock, pixi.toml
See https://ribasim.org/changelog
=> Update dependencies; switch to Ribasim v2025.2.0

notebooks/brabantse_delta/01_fix_model.py, notebooks/samenvoegen_modellen.py, src/ribasim_nl/ribasim_nl/reset_index.py
- 1_fix_model.py of WBD fixed (out-of-scope)
- renamed `model` `model_spec` as the model is reserved for `ribasim_nl.Model` objects
- hint to removing results if update_state() results in obsolete missing node_ids in basin / State
So be aware, you may have to remove the results of WBD,Dommel, DOD and Vechtstromen for the script to succeed.
Resulting LHM model is here: https://deltares.thegood.cloud/s/KM36QRKSy95PJ9H
@rbruijnshkv, be aware Fryslan model-version 2025.3.3 still has duplicated links in opposite source-destination
=> Samenvoegen 20250318

src/peilbeheerst_model/Parametrize/Zuiderzeeland_parametrize.py
Fixed water supply ("aanvoer") for the entire region of Waterschap Zuiderzeeland
=> Aanvoer_Zuiderzeeland

src/peilbeheerst_model/Parametrize/AmstelGooienVecht_parametrize.py, src/peilbeheerst_model/Parametrize/Delfland_parametrize.py, src/peilbeheerst_model/Parametrize/HollandsNoorderkwartier_parametrize.py, src/peilbeheerst_model/Parametrize/HollandseDelta_parametrize.py, src/peilbeheerst_model/Parametrize/Rijnland_parametrize.py, src/peilbeheerst_model/Parametrize/Rivierenland_parametrize.py, src/peilbeheerst_model/Parametrize/Scheldestromen_parametrize.py, src/peilbeheerst_model/Parametrize/SchielandendeKrimpenerwaard.py, src/peilbeheerst_model/Parametrize/WetterskipFryslan_parametrize.py, src/peilbeheerst_model/Parametrize/Zuiderzeeland_parametrize.py
This will work anywhere provided `ribasim.exe` is in the Path.
=> Remove absolute ribasim exe path

pixi.lock
|Dependency[^1]|Before|After|Change|
|-|-|-|-|
|[libgfortran](https://prefix.dev/channels/conda-forge/packages/libgfortran)|5.0.0|14.2.0|Major Upgrade|
|[libgfortran5](https://prefix.dev/channels/conda-forge/packages/libgfortran5)|h6c33f7e_103|h2c44a93_105|Only build string|
[^1]: **Bold** means explicit dependency.
[^2]: Dependency got downgraded.
=> Update pixi lockfile

scripts/add_lhm_budgets/get_data_LHM_run.py, src/ribasim_nl/ribasim_nl/assign_offline_budgets.py
Update chunks + filename for using LHM budgets
=> Update chunks + filename for using LHM budgets

src/ribasim_nl/ribasim_nl/analyse_results.py
- Added the cumulative discharge to the figures used for validation.
- Gaps in the measured timeseries are filled by taking the last measured value for every gap. This ensures that the cumulative discharge can roughly be compared to the modelled cumulative discharge, although with caution.
- Minor visual changes to the figures
=> Cumulative discharge for validation figures
