Deltares/Ribasim-NL

.gitignore, .pre-commit-config.yaml, .typos.toml, .vscode/extensions.json, .vscode/settings.json, environment.yml, pixi.lock, ruff.toml, src/hydamo/hydamo/datamodel.py, src/hydamo/pyproject.toml, src/ribasim_nl/pyproject.toml, src/ribasim_nl/ribasim_nl/cloud.py, src/ribasim_nl/ribasim_nl/codes.py, src/ribasim_nl/ribasim_nl/geometry.py
This is a bit of a mixed bag of changes similar to which we merged in https://github.com/Deltares/Ribasim last weeks.
First of all we now require at least Python 3.10. Before this was 3.9. The differences are not too big, but I don't think we need to spend out time supporting old Python versions at this moment, 3.10 is sufficiently old.
Since we now tell ruff to target Python 3.10, and ask it to give syntax upgrade suggestions, we fix those. Most of this is nicer typing annotations, using e.g. `dict` instead of `from typing import Dict`. The ruff updates also includes some configuration to make it work well with notebooks.
Lastly I removed the typos check. I don't think it is suitable for this repository as there are many Dutch terms used in the code and docs.
=> require Python 3.10 and associated ruff updates

.github/workflows/docs.yml, .github/workflows/python_lint.yml, .github/workflows/python_tests.yml, open-vscode-dev.bat, open-vscode.bat, pixi.lock, pixi.toml
Fixes #84.
This adds a Pixi `dev` environment, which points to the Ribasim repository, which is expected to be cloned next to this repository. To launch VSCode in this environment, use `open-vscode-dev.bat`. I added `open-vscode.bat` as well to open the default environment, which points to the latest ribasim release.
https://pixi.sh/latest/reference/configuration/#the-feature-and-environments-tables
=> Support Ribasim checkout

notebooks/aaenmaas/get_model.py, notebooks/de_dommel/get_model.py, notebooks/de_dommel/get_verwerkt.py, notebooks/de_dommel/modify_model.py, pixi.lock, src/ribasim_nl/ribasim_nl/__init__.py, src/ribasim_nl/ribasim_nl/model.py, src/ribasim_nl/ribasim_nl/network_validator.py
Contains all work for #102, including:
- NetworkValidator to automated fixing of topological issues
- Misc new methods for the Ribasim-NL Model class:
- `reverse_edge`: reverse an edge and it's `from` and `to`properties
- `remove_node` remove a node, possibility to remove connected_edges as well
- `remove_edge`: remove an edge, possibility to remove disconnected_nodes as well
- the modify_model.py script to work from Sweco 2024.6.3 model to 2024.8.0 available at https://deltares.thegood.cloud/f/117827
All results in a topologically correct network that passes the RIBASIM network validator and simulation. Note, all parameters are implausible still:
=> Fix dommel network

pixi.lock, pixi.toml
Fixes #122.
At this point we'll work with the already uploaded results of ribasim_lumping and patch those up for use with the current Ribasim version, like for instance done in #129.
That means for now we don't need to update this code to run. I don't delete the code because we probably want to use it later on and may need to look at the implementation. This does mean we cannot `import ribasim_lumping` within the pixi environment.
Also updates dependencies with `pixi update`.
=> Disconnect ribasim_lumping for now

notebooks/de_dommel/01_fix_model_network.py, notebooks/de_dommel/03_fix_basin_area.py, notebooks/de_dommel/04_parameterize_model.py, notebooks/de_dommel/05_add_berging.py, notebooks/de_dommel/99_upload_model.py, src/ribasim_nl/ribasim_nl/__init__.py, src/ribasim_nl/ribasim_nl/geometry.py, src/ribasim_nl/ribasim_nl/model.py
Een model van De Dommel met bergingsknopen volgens methode Vd Gaast. Resulteert in model DeDommel versie 2024.9.0, beschikbaar via: https://deltares.thegood.cloud/f/119263
fixes/updates:
- #102
- #157
- #97
=> De Dommel met bergend gebied

src/peilbeheerst_model/peilbeheerst_model/preprocess_data/AmstelGooienVecht.ipynb
Instead of local paths, this uses the CloudStorage class from the `ribasim_nl` package to load AGV data, such that this code can also run on other machines.
I uncommented the first processing part since that was needed for the second part to run.
This also adds an upload of the processed data to the cloud to `AmstelGooienVecht/verwerkt/preprocessed.gpkg`, so the result of this step is directly accesible as well.
It should not change and results, but it's good to go over this with @rbruijnshkv tomorrrow.
=> Make AGV preprocessing reproducible

docs/workflow/level-controlled.qmd, src/peilbeheerst_model/01_parse_crossings.py, src/peilbeheerst_model/01b_ad_krw_to_peilgebieden.py, src/peilbeheerst_model/parse_crossings/AmstelGooienVecht.py
This creates a new script `src\peilbeheerst_model\parse_crossings\AmstelGooienVecht.py` that is hooked up to thegoodcloud.
I left the one with all waterboards intact. In the new script I didn't include the plotting code.
=> AGV reproducible parse_crossings

src/peilbeheerst_model/02_crossings_to_ribasim_notebook.py, src/peilbeheerst_model/03_test_outlets.py, src/peilbeheerst_model/Parametrize/AmstelGooienVecht_parametrize.py
Fixes #124.
This only removes lines because the imports didn't seem to be used.
=> Remove import workarounds

notebooks/noorderzijlvest/02_parameterize_model.py, src/peilbeheerst_model/peilbeheerst_model/controle_output.py, src/peilbeheerst_model/peilbeheerst_model/data/output_controle.qlr, src/peilbeheerst_model/peilbeheerst_model/shortest_path.py, src/ribasim_nl/ribasim_nl/parametrization/level_boundary_table.py, src/ribasim_nl/ribasim_nl/parametrization/parameterize.py
Deze levert een controle van de resultaten op die worden gegenereerd met het noorderzijlvest/02_parameterize_model.py-script. Plaatje ziet er zo uit:
=> controle NZV model

src/ribasim_nl/ribasim_nl/model.py
Since it is now `from ribasim.geometry.link import NodeData`.
=> Remove type assert that is broken by edge to link rename

.github/workflows/pixi_auto_update.yml, .github/workflows/pre-commit_auto_update.yml
This is the same as what we use in the Ribasim repo. It updates the our pixi lock file once a month to make sure we are using recent packages.
I'm also changing the pre-commit update on the same time, such that there is less chance of a difference in pre-commit results on CI and locally.
@evetion can you make a CI_PR_PAT for this repo as well? Or would it make sense to have such a PAT org-wide?
=> Add pixi auto update action

pixi.lock
<details>
<summary>Explicit dependencies</summary>
|Dependency[^1]|Before|After|Change|Environments|
|-|-|-|-|-|
|[**pandera**](https://prefix.dev/channels/conda-forge/packages/pandera)|0.22.1|0.23.0|Minor Upgrade|*all*|
|[**python**](https://prefix.dev/channels/conda-forge/packages/python)|3.12.8|3.13.2|Minor Upgrade|*all envs* on win-64|
|[**matplotlib**](https://prefix.dev/channels/conda-forge/packages/matplotlib)|3.10.0|3.10.1|Patch Upgrade|*all*|
|[**pip**](https://prefix.dev/channels/conda-forge/packages/pip)|25.0|25.0.1|Patch Upgrade|*all*|
|[**pyarrow**](https://prefix.dev/channels/conda-forge/packages/pyarrow)|19.0.0|19.0.1|Patch Upgrade|*all*|
|[**pytest**](https://prefix.dev/channels/conda-forge/packages/pytest)|8.3.4|8.3.5|Patch Upgrade|*all*| …
=> Update pixi lockfile

notebooks/aa_en_maas/03_parameterize_model.py, src/peilbeheerst_model/peilbeheerst_model/controle_output.py
Idealiter blijven dingen backward compatible. Wij kunnen nu `controle_output.run_all()` niet draaien omdat we wat nieuwe boolean kolommen missen in tabellen. Ik heb dat nu opgelost door `controle_output.run_aanvoer()` toe te voegen. Ik ga ervan uit dat er zo niets omvalt aan HKV-zijde
=> fixed on AAM

src/peilbeheerst_model/peilbeheerst_model/ribasim_feedback_processor.py
Modifications to the `Link` (previously `Edge`) is still referred to as `Edge`. Therefore, handling of the feedback forms should enable backward compatibility by allowing both keywords: `Edge` and `Link`.
=> Backward compatibility for handling feedback forms

src/peilbeheerst_model/Parametrize/AmstelGooienVecht_parametrize.py, src/peilbeheerst_model/Parametrize/Delfland_parametrize.py, src/peilbeheerst_model/Parametrize/HollandsNoorderkwartier_parametrize.py, src/peilbeheerst_model/Parametrize/HollandseDelta_parametrize.py, src/peilbeheerst_model/Parametrize/Rijnland_parametrize.py, src/peilbeheerst_model/Parametrize/Rivierenland_parametrize.py, src/peilbeheerst_model/Parametrize/Scheldestromen_parametrize.py, src/peilbeheerst_model/Parametrize/SchielandendeKrimpenerwaard.py, src/peilbeheerst_model/Parametrize/Zuiderzeeland_parametrize.py, src/peilbeheerst_model/peilbeheerst_model/assign_authorities.py
Added a column in the LevelBoundary.static named meta_couple_authority, which automatically searches for the correct water authority (waterschappen or Rijkswaterstaat) to be coupled with. Individual nodes can be overwritten by using the optional custom_nodes variable.
=> Column meta_couple_authority

.github/workflows/docs.yml, .github/workflows/pixi_auto_update.yml, .github/workflows/pre-commit_auto_update.yml, .github/workflows/python_lint.yml, .github/workflows/python_tests.yml
Follow up to #304. We no longer need to checkout the Ribasim repository besides this on to be able to run CI.
=> Simplify CI without dev environment

src/peilbeheerst_model/Parametrize/Delfland_parametrize.py
Brielse Meer was modelled as `Basin` for Delfland, which caused coupling issues with Hollandse Delta. Therefore, the `Basin` Brielse Meer has been removed and substituted by a `LevelBoundary`. The connected `Pump` is set to _aanvoer_-only.
=> Delfland couple-ready: Changing Brielse Meer from `Basin` to `LevelBoundary`

scripts/add_lhm_budgets/get_data_LHM_run.py, src/ribasim_nl/ribasim_nl/assign_offline_budgets.py
This PR updates:
The get_data_LHM_run.py script for:
1- Getting the latest LHM 4.3.3 release budgets from the LHM server. 
2- Adding the MetaSWAP budgets for runoff and surface water irrigation
3- Rechunking the data more spatially so lazy evaluation is more effective in case of water board scale models. 
The AssignOfflineBudgets-class for:
1- Dealing with the new zarr file
2- Dealing with the extra MetaSWAP budgets for secondary basins
=> Update LHM budgets related scripts

docs/_quarto.yml, docs/dev/index.qmd
On setting up a developer environment with Pixi, including instructions on how to use a local or unreleased Ribasim for testing.
=> Add developer docs

notebooks/samenvoegen_modellen.py
Rather than individual models or all combined, that adds the option to write per RDO (Regionaal Droogte Overleg). This is mainly useful as an intermediate stage to investigate scaling and performance issues.
Some water authorities are in multiple RDOs, but I assigned them to one, mainly such that the sizes are more similar.
It also refactors the code a bit to make it use functions.
=> Samenvoegen_modellen: support writing RDO grouped models
